name: CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: update pricedb
        run: ./update_price_db.sh
      - name: make git use credentials file
        run: git config credential.helper "store --file=.git/credentials"
      - name: set up github credentials
        run: echo "https://${GITHUB_TOKEN}:@github.com" > .git/credentials
      - name: push changes
        run: ./push.sh $GITHUB_TOKEN
